Repository UMC-TRIPY/back-end-spring, pull requests merged in 2024-05, with the labels that each got.

#55 Hotfix: Cors 에러 해결
  src/main/java/com/example/tripy/TripyApplication.java
Labels: fix

#53 Feat: 화폐 & 날씨 API 구현
  src/main/java/com/example/tripy/domain/country/Country.java
  src/main/java/com/example/tripy/domain/currency/Currency.java
  src/main/java/com/example/tripy/domain/currency/CurrencyRepository.java
  src/main/java/com/example/tripy/domain/currency/CurrencyService.java
  src/main/java/com/example/tripy/domain/currency/dto/CurrencyResponseDto.java
  src/main/java/com/example/tripy/domain/wheather/WeatherController.java
  src/main/java/com/example/tripy/domain/wheather/WeatherRepository.java
  src/main/java/com/example/tripy/domain/wheather/WeatherService.java
  src/main/java/com/example/tripy/domain/wheather/dto/WheatherResponseDto.java
Labels: feat

#58 Feat: 내 여행 가방 목록 상세 조회, 여행 가방 개별 상세 조회 API
  src/main/java/com/example/tripy/domain/bag/BagController.java
  src/main/java/com/example/tripy/domain/bag/BagService.java
  src/main/java/com/example/tripy/domain/bag/dto/BagResponseDto.java
  src/main/java/com/example/tripy/domain/cityplan/CityPlanRepository.java
  src/main/java/com/example/tripy/domain/countrymaterial/CountryMaterialService.java
  src/main/java/com/example/tripy/domain/material/dto/MaterialResponseDto.java
Labels: feat

#63 Refactor: 가방 API 멤버 어노테이션 추가 및 로직 수정
  src/main/java/com/example/tripy/domain/bag/BagController.java
  src/main/java/com/example/tripy/domain/bag/BagRepository.java
  src/main/java/com/example/tripy/domain/bag/BagService.java
Labels: refactor

#69 Feat: 가방 추가 API 응답 추가
  src/main/java/com/example/tripy/domain/bag/BagController.java
  src/main/java/com/example/tripy/domain/bag/BagService.java
  src/main/java/com/example/tripy/domain/bag/dto/BagResponseDto.java
Labels: feat
